server:
  port: 8080


spring:
  redis:
    port: 6379
    password: 123456
    host: 192.168.211.129
    jedis:
      pool:
        max-idle: 6      #??��??????????
        max-active: 10   #????????????
        min-idle: 2      #??��??????
    timeout: 2000        #??????

